site_name: QGIS OACS plugin
site_url: https://byteroad.github.io/qgis-oacs-plugin
repo_url: https://github.com/byteroad/qgis-oacs-plugin

nav:
  - Home: "index.md"
  - User guide: "user-guide.md"
  - Development: "development.md"
  - Changelog: "changelog-base.md"
  - QGIS Repo: "repo/plugins.xml"
  - Third-party credits: "third-party.md"
  - Known OACS servers: "known-servers.md"

theme:
  name: material
  logo: images/graph_3.svg
  favicon: images/graph_3.svg
  font:
    text: Montserrat
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
        
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: lime
      accent: teal

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: lime
      accent: teal

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.snippets:
      base_path: .
  - pymdownx.details
  - pymdownx.superfences
  - admonition

plugins:
  - search
